### ISSUE TITLE
购买后不能登录

### ISSUE THREAD

**Issue by guzuping523** [getlantern/forum#1640]
上午10点27分支付宝付款购买1年，通过”点击登录“使用注册账户登录，提示找不到，有人能帮忙解决下吗？ 付款支付宝koolfaye@163.com  难道是注册账户填错...    如果没错应该是109916723@qq.com

**Comment by guzuping523** [comment]
@p3rcya

**Comment by sunking1111** [comment]
我也是同样的问题  2016年10月25日晚九点左右购买，目前卸载很多次啦，一直无法加载网页，全部打不开，只是官网右下角显示绿色正常的标志；请大神解决；安卓的目前正常登陆，youtube很慢打开

**Comment by p3rcya** [comment]
@guzuping523 后台没有找到付款记录。请确认下支付宝确认成功，没有退款。 请上传下付款成功的截图

**Comment by guzuping523** [comment]
@p3rcya  确定支付成功且没有退款

![360 20161026074659](https://cloud.githubusercontent.com/assets/11645843/19708391/d2260d8a-9b50-11e6-9707-3c0f70a8fa67.jpg)
![360 20161026074753](https://cloud.githubusercontent.com/assets/11645843/19708392/d236290e-9b50-11e6-89e8-9ef94f4d48a6.jpg)

**Comment by orbancanon** [comment]
@guzuping523 很奇怪我们在后台和Stripe那边完全没有找到这笔付款相关的信息，甚至在这个时间点前后都看了也没有。能否把你的settings文件发一下以便查找相关线索？邮件到orbancanon@gmail.com

Mac: `cat ~/Library/Application\ Support/Lantern/settings.yaml`
Windows: `C:\Users\<username>\AppData\Roaming\lantern\settings.yaml`

**Comment by guzuping523** [comment]
@orbancanon  settings.yaml 发过去了，付款后我尝试卸载重装过1次。

**Comment by orbancanon** [comment]
@guzuping523 支付宝拒绝了这笔付款。详情已回复你邮件。

**Comment by guzuping523** [comment]
@orbancanon 下午已收到支付宝退款，感谢帮助.

**Comment by sunking1111** [comment]
附件里是购买记录 ，支付宝账号531809385@qq.com发自网易邮箱大师
            在2016年10月26日 02:10，p3rcya 写道:@guzuping523 后台没有找到付款记录。请确认下支付宝确认成功，没有退款。 请上传下付款成功的截图

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/getlantern/forum","title":"getlantern/forum","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/getlantern/forum"}},"updates":{"snippets":[{"icon":"PERSON","message":"@p3rcya in #1640: @guzuping523 后台没有找到付款记录。请确认下支付宝确认成功，没有退款。 请上传下付款成功的截图"}],"action":{"name":"View Issue","url":"https://github.com/getlantern/forum/issues/1640#issuecomment-256112029"}}}
